name = "BetterMC-BMC5"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fa2bd6c8018fba4f0d5b238321cc7756b476ed19f4cd7f7a6cb4b4e55e35bd0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = []
