name = "BetterMC-BMC5"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b2797b3ca15443314df42f3f3c34891b7e5406e66b40a67b2159f1a13468b31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = []
