name = "BetterMC-BMC5"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6295020bed8dddd87c7754a0f50ac02a88865740c0c3414d39f1839ef15bd63"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = []
